server:
  port: 7000
  context-path: /bs
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  mvc:
    static-path-pattern: /**
path:
  resources:
    static-locations: file:/Users/raines/Desktop/my/demo